spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: springcloud-dept
  datasource:
    password: 123456
    druid:
      min-idle: 1
      test-on-borrow: true
      stat-view-servlet:
        allow: true
      max-active: 20
      initial-size: 1
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB02?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis.cig.xml
  type-aliases-package: com.longer.springcloud.entity
eureka:
  instance:
    instance-id: springcloud-probider-dept-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
info:
  app:
    name: springcloud-provider-dept-8001
  build:
    artifactId: $project.artifactId$
    version: $project.version$
  companny:
    name: www.atguigu.com
---
mybatis:
    config-location: classpath:mybatis/mybatis.cig.xml
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.longer.springcloud.entity
server:
    port: 8001
spring:
    application:
        name: springcloud-dept
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            initial-size: 1
            max-active: 20
            min-idle: 1
            stat-view-servlet:
                allow: true
            test-on-borrow: true
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/cloudDB02?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
    profiles: test
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
        instance-id: springcloud-probider-dept-8001
        prefer-ip-address: true
info:
    app:
        name: springcloud-provider-dept-8001
    build:
        artifactId: '$project.artifactId$'
        version: '$project.version$ '
    companny:
        name: www.atguigu.com